# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class BasinShort(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, basin_id: int=None, name: str=None):  # noqa: E501
        """BasinShort - a model defined in Swagger

        :param basin_id: The basin_id of this BasinShort.  # noqa: E501
        :type basin_id: int
        :param name: The name of this BasinShort.  # noqa: E501
        :type name: str
        """
        self.swagger_types = {
            'basin_id': int,
            'name': str
        }

        self.attribute_map = {
            'basin_id': 'basinId',
            'name': 'name'
        }
        self._basin_id = basin_id
        self._name = name

    @classmethod
    def from_dict(cls, dikt) -> 'BasinShort':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BasinShort of this BasinShort.  # noqa: E501
        :rtype: BasinShort
        """
        return util.deserialize_model(dikt, cls)

    @property
    def basin_id(self) -> int:
        """Gets the basin_id of this BasinShort.


        :return: The basin_id of this BasinShort.
        :rtype: int
        """
        return self._basin_id

    @basin_id.setter
    def basin_id(self, basin_id: int):
        """Sets the basin_id of this BasinShort.


        :param basin_id: The basin_id of this BasinShort.
        :type basin_id: int
        """

        self._basin_id = basin_id

    @property
    def name(self) -> str:
        """Gets the name of this BasinShort.


        :return: The name of this BasinShort.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this BasinShort.


        :param name: The name of this BasinShort.
        :type name: str
        """

        self._name = name
