[
    {
        "id": "2dd09457672f8c47",
        "type": "tab",
        "label": "daq-final",
        "disabled": false,
        "info": "",
        "env": []
    },
    {
        "id": "1d1ec64ae90df284",
        "type": "mqtt in",
        "z": "2dd09457672f8c47",
        "name": "Room 315 - PM2.5",
        "topic": "public/cpe/room315/pm25",
        "qos": "0",
        "datatype": "auto-detect",
        "broker": "1d5192608b36f864",
        "nl": false,
        "rap": true,
        "rh": 0,
        "inputs": 0,
        "x": 330,
        "y": 240,
        "wires": [
            [
                "a7141ebe53f90ccc",
                "397ca3fc6b29019a"
            ]
        ]
    },
    {
        "id": "a7141ebe53f90ccc",
        "type": "debug",
        "z": "2dd09457672f8c47",
        "name": "PM2.5",
        "active": false,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "payload",
        "targetType": "msg",
        "statusVal": "",
        "statusType": "auto",
        "x": 570,
        "y": 360,
        "wires": []
    },
    {
        "id": "397ca3fc6b29019a",
        "type": "ui_gauge",
        "z": "2dd09457672f8c47",
        "name": "",
        "group": "be9d36db70f61695",
        "order": 0,
        "width": 0,
        "height": 0,
        "gtype": "gage",
        "title": "Room 315 PM2.5",
        "label": "ug/m3",
        "format": "{{value}}",
        "min": 0,
        "max": "500",
        "colors": [
            "#00b500",
            "#e6e600",
            "#ca3838"
        ],
        "seg1": "",
        "seg2": "",
        "className": "",
        "x": 610,
        "y": 240,
        "wires": []
    },
    {
        "id": "3bff6d3a3cf74735",
        "type": "ui_gauge",
        "z": "2dd09457672f8c47",
        "name": "",
        "group": "be9d36db70f61695",
        "order": 0,
        "width": 0,
        "height": 0,
        "gtype": "gage",
        "title": "Room 502 - ambient noise",
        "label": "dB",
        "format": "{{value}}",
        "min": 0,
        "max": "80",
        "colors": [
            "#00b500",
            "#e6e600",
            "#ca3838"
        ],
        "seg1": "",
        "seg2": "",
        "className": "",
        "x": 660,
        "y": 440,
        "wires": []
    },
    {
        "id": "43eb952f9325ed65",
        "type": "mqtt in",
        "z": "2dd09457672f8c47",
        "name": "Room 502 - ambiance",
        "topic": "public/cpe/room502/noise",
        "qos": "0",
        "datatype": "auto-detect",
        "broker": "1d5192608b36f864",
        "nl": false,
        "rap": true,
        "rh": 0,
        "inputs": 0,
        "x": 340,
        "y": 440,
        "wires": [
            [
                "3bff6d3a3cf74735",
                "f9aecb2fda0365f3"
            ]
        ]
    },
    {
        "id": "f9aecb2fda0365f3",
        "type": "debug",
        "z": "2dd09457672f8c47",
        "name": "Noise",
        "active": false,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "payload",
        "targetType": "msg",
        "statusVal": "",
        "statusType": "auto",
        "x": 590,
        "y": 500,
        "wires": []
    },
    {
        "id": "1d5192608b36f864",
        "type": "mqtt-broker",
        "name": "KU IOT CPE",
        "broker": "http://iot.cpe.ku.ac.th/",
        "port": "1883",
        "clientid": "b6310545426",
        "autoConnect": true,
        "usetls": false,
        "protocolVersion": "4",
        "keepalive": "60",
        "cleansession": true,
        "birthTopic": "",
        "birthQos": "0",
        "birthPayload": "",
        "birthMsg": {},
        "closeTopic": "",
        "closeQos": "0",
        "closePayload": "",
        "closeMsg": {},
        "willTopic": "",
        "willQos": "0",
        "willPayload": "",
        "willMsg": {},
        "userProps": "",
        "sessionExpiry": ""
    },
    {
        "id": "be9d36db70f61695",
        "type": "ui_group",
        "name": "Sensors",
        "tab": "c3dabb4d8280066b",
        "order": 1,
        "disp": true,
        "width": "6",
        "collapse": false,
        "className": ""
    },
    {
        "id": "c3dabb4d8280066b",
        "type": "ui_tab",
        "name": "Final Exam",
        "icon": "dashboard",
        "order": 1,
        "disabled": false,
        "hidden": false
    }
]
